version: '3'

services:
    app:
        build: .
        container_name: app
        #entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
        #environment:
        #    - DB_HOST=db
        #    - DB_PORT=3306
        #    - DB_DATABASE=laravel
        #    - DB_USERNAME=root
        #    - DB_PASSWORD=root
        #    - REDIS_HOST=redis
        #    - REDIS_PASSWORD=null
        #    - REDIS_PORT=6379
        #    - APP=app:9000
        volumes:
            - .:/var/www
        networks: 
            - dependecias
        depends_on: 
            - db
            - redis
    
    nginx: 
        build: .docker/nginx
        container_name: nginx
        restart: always
        tty: true
        #entrypoint: dockerize -template /var/www/.docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf nginx -g "daemon off;"
        #environment:
        #    - NG_PORT=9000
        #    - NG_APPNAME=app
        ports: 
            - "8000:80"
        volumes: 
            - .:/var/www
        networks:
            - dependecias
        depends_on: 
            - app

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks:
            - dependecias

    redis:
        image: redis:alpine
        expose:
            - 6379
        networks: 
            - dependecias

networks: 
    dependecias:
        driver: bridge
